### ISSUE TITLE
wiki/Configuring-OAUTH empty

### ISSUE THREAD

**Issue by pitbulk** [helpyio/helpy#1210]
The Readme mentions a WIki page for "configuring omniauth"
but that wiki page is empty:  https://github.com/helpyio/helpy/wiki/Configuring-OAUTH

**Comment by chileshemartin** [comment]
Strange. I think it has been removed. But if you go to the settings file [here](https://github.com/chileshemartin/help/blob/master/config/settings.yml) , you will find commneted examples under omniauth. If you just uncomment one of them and provide the id and secret it should work. A list of valid strategies with the corespongin gem installations is found [here](https://github.com/omniauth/omniauth/wiki/List-of-Strategies)

**Comment by pitbulk** [comment]
I miss a more detailed documentation specific for helpy.

Devise/Omniauth has multiple ways to be implemented.

In our specific scenario, omniauth-saml that settings and its specific confir loader is not enough because SAML has different parameters than key/secret.

I found the omniauth support on helpy very limited.

**Comment by pitbulk** [comment]
I guess the doc is this one.
https://support.helpy.io/en/knowledgebase/11-Installing-Helpy/docs/19-Setting-Up-OAUTH-for-your-Helpy

**Comment by scott** [comment]
Check this out https://github.com/helpyio/helpy/wiki/SSO--Configuring-OAUTH . The name/url is different.

**Comment by pitbulk** [comment]
Thanks @scott, then you should update the Readme.

I tried to configure a [SAML Omniauth provider](https://github.com/omniauth/omniauth-saml) that is kinda different than an oauth2 provider.

It has different settings parameters than the pair `id` and `secret`

So far I added its settings to the config/settings.yml file
```
omniauth:
  providers:
    saml:
      issuer: "http://localhost/users/auth/saml/metadata"
      assertion_consumer_service_url: "http://localhost/users/auth/saml/callback"
      single_logout_service_url: "http://localhost/users/auth/saml/sls"
      idp_entity_id: "<idp_entity_id here>"
      idp_sso_target_url: "<idp_entity_sso here>"
      idp_slo_target_url: "<idp_entity_slo here>"
      idp_cert: "<x509 cert here>"
      name_identifier_format: "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
      uid_attribute: "User.email"
      attribute_statements: {email: 'User.email', uid: 'Username', name: 'User.FirstName', first_name: 'User.FirstName', last_name: 'User.LastName'}
```

I then edited config/initializers/devise.rb to be able read those settings.
```
# ==> OmniAuth
  # Add a new OmniAuth provider. Check the wiki for more information on setting
  # up on your models and hooks.
  # config.omniauth :google_oauth2, 'APP_ID', 'APP_SECRET', scope: 'user:email'
  unless Settings.omniauth.nil? || Settings.omniauth.providers.nil?
    Settings.omniauth.providers.each do |provider|
      if provider[0].eql?(:saml)
        config.omniauth provider[0],
          :assertion_consumer_service_url => provider[1].assertion_consumer_service_url,
          :issuer => provider[1].issuer,
          :single_logout_service_url => provider[1].single_logout_service_url,
          :idp_sso_target_url => provider[1].idp_sso_target_url,
          :idp_slo_target_url => provider[1].idp_slo_target_url,
          :idp_sso_target_url_runtime_params => {:original_request_param => :mapped_idp_param},
          :idp_cert => provider[1].idp_cert,
          :name_identifier_format => provider[1].name_identifier_format,
          :uid_attribute => provider[1].uid_attribute,
          :attribute_statements => provider[1].attribute_statements
      else
        config.omniauth provider[0], provider[1].id, provider[1].secret, scope: 'user:email'
      end
    end
  end
```

And finally I added at app/controllers/omniauth_callbacks_controller.php
```
  def saml
    auth_hash = env["omniauth.auth"]
    user = User.find_by(uid: auth_hash[:uid])

    sign_in_and_redirect user
  end
```

but then I got:
```
ActionController::InvalidAuthenticityToken
```

I read this [post](https://github.com/plataformatec/devise/issues/3119) and already tried to add
```
protect_from_forgery with: :exception, except: [:saml]
```
On aplication_controller.rb and at omniauth_callbacks_controller.rb with no luck

@scott do you know how to solve this? is your app extra protecting from CSRF attacks with something different than the protect_from_forgery defined on the app controller?
